name: CI
on: [push]
jobs: 
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Action
        id: hello
        uses: ./
        with: 
          myInput: 'Stav'
      - name: Output
        run: |
          echo ${{ steps.hello.outputs.memory }}
          echo "Total memory successfully output"
          
